<!DOCTYPE html><html><head><title><?php echo htmlspecialchars(千社札.com, ENT_QUOTES, 'UTF-8'); ?></title><?php wp_enqueue_style('style', get_stylesheet_uri(), array(), time() );
wp_head();?><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div class="page"><div class="page__header"><div class="page__topHeader"><div class="topHeader"><div class="topHeader__siteTitleBorder"><div class="siteTitleBorder__siteTitle">千社札.com</div></div><div class="topHeader__go2English"><div class="go2English"><a href="#">Go to English page</a></div></div></div></div></div><div class="page__content"><div class="page__main"><div class="homeHeaderImg"><img src="https://placehold.jp/500x300.png"></div><div class="contentBox--botMargin"><h2 class="contentBox--botMargin__title">千社札とは？</h2><div class="contentBox--botMargin__image"><img src="https://placehold.jp/400x300.png"></div><div class="contentBox--botMargin__desc">千社札と書いて「せんじゃふだ(せんしゃふだ)」と読みます。世の中の安泰と家内安全を願う千社参りの札を、略して千社札というようになったとされています。当店ではこの千社札をシール・ストラップ・名刺にして、銀座歌舞伎座の向かいで販売しています。</div></div><div class="cardLists--blue"><?php $parent_id = get_page_by_title('人気商品')->ID;   
$args = array( 
  'post_type' => 'page',
  'post_parent' => $parent_id,
        );

$the_query = new WP_Query( $args );?><div class="cardLists__title"><div>当店の人気商品</div></div><?php while($the_query->have_posts()) : $the_query->the_post(); ?><div class="cardLists__card"><div class="card"><h3 class="card__title"><?= the_title(); ?></h3><div class="card__wrap"><div class="card__desc"><?= the_content(); ?></div><div class="card__img"><img src="https://placehold.jp/400x300.png"></div></div><div class="card__price"> <?= get_post_meta(get_the_ID(), 'price', true); ?></div><div class="card__showMoreDetail"><a href="">詳しく見る>></a></div></div></div><?php endwhile; ?></div><div class="cardLists--red"><?php $parent_id = get_page_by_title('購入事例')->ID;   
$args = array( 
  'post_type' => 'page',
  'post_parent' => $parent_id,
        );

$the_query = new WP_Query( $args );  ?><div class="cardLists__title"><div>ご購入事例の紹介</div></div><?php while($the_query->have_posts()) : $the_query->the_post(); ?><div class="cardLists__card"><div class="card"><h3 class="card__title"><?= the_title(); ?></h3><div class="card__wrap"><div class="card__desc"><?= the_content(); ?></div><div class="card__img"><img src="https://placehold.jp/400x300.png"></div></div></div></div><?php endwhile; ?></div><div class="newsLists"><div class="newsLists__title"><div>新着情報・メディア掲載</div></div><?php while(have_posts()): the_post(); ?><div class="newsLists__newsBox"><div class="newsBox"><div class="newsBox__img"><img src="https://placehold.jp/50x120.png"></div><div class="newsBox__title"><?= the_title(); ?></div></div></div><?php endwhile; ?></div><div class="contentBox--botMargin"><h2 class="contentBox--botMargin__title">毎日更新！FaceBookやってます！</h2><div class="contentBox--botMargin__images"><div class="images"><div class="image"><img src="https://placehold.jp/500x300.png"></div><div class="image"><img src="https://placehold.jp/500x300.png"></div></div></div><p class="contentBox--botMargin__desc--full">Facebookに、お店に来てくださった外国人のお客様の写真をアッ プしております。</p><div class="contentBox--botMargin__button"><a href="">Facebook/senjafuda</a></div></div></div><div class="page__sidebar"></div></div><div class="page__footer"></div></div></body></html>